name: CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Solution Folder  
      run:  rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        echo Release folder
        ls -la
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: |
              .
              !.git*
              !*.sln 
              !*.props 
              !./Solutions/*.txt
              !./*/*Dbl/
              !./*/*Documents/*.cpp
              !./*/*Documents/*.h
              !./*/*Documents/*.dex
              !./*/*Documents/*.vcxproj
              !./*/*Documents/*.filters
              !./*/*.h
